### ISSUE TITLE
Unclear Description of MD5 checks

### ISSUE THREAD

**Issue by GiuseppeChillemi** [mmarcincin/HB-DRM-free-bulk-downloader#11]
Hi,
 I have read the description for MD5 checks and there is something missing: what will happen next.

md5 global switches:

!md5+ (default, enable md5 file integrity check)
//// It is not clear what the script will do if MD5 fails: redownload ? (how many attempts?) warns only ? 
!md5- (disable md5 file integrity check)
!md5s+ (default, enable md5 hash check/file integrity of previously stored/downloaded files, disabled if you use !md5-)
/// Same as above, plus: will it check previously downloaded files AND new downloads or just only previously downloaded files ?
!md5s- (disable md5 hash check/file integrity of previously stored/downloaded files)

**Comment by GiuseppeChillemi** [comment]
Addition to the above notes:

!md5+ (default, enable md5 file integrity check)
!md5- (disable md5 file integrity check)
/// Does it disable ALL MD5 checks, already downloaded and file to download, or only the latter ?
!md5s+ (default, enable md5 hash check/file integrity of previously stored/downloaded files, disabled if you use !md5-)
//// for "disabled if you use !md5-" do you mean that using "!md5-" you will disable both "downloaded" and "to download" checks ?
!md5s- (disable md5 hash check/file integrity of previously stored/downloaded files)
//// does it work for both "downloaded and to download" like the previous switch or just for "downloaded" ? And once you use it, wich will be the fallback behaviour ? No check or check only in  files to download ? (!md5+)

**Comment by mmarcincin** [comment]
I'll add to the readme that it's for log only for now.
Settings never return to default if modified in links.txt, you need to use the opposite switch if you want to change the behavior.
For example if you add !md5- at the start of the links.txt, it'll disable md5 file integrity check for the whole run unless modified again with !md5+.
I'll probably add some separate example file for links.txt too.

**Comment by GiuseppeChillemi** [comment]
Global Switches are per script basis, aren't they?

However, a "reset" switch to return to default in a script would be welcome!

**Comment by mmarcincin** [comment]
yes, they change the behaviour until they are changed again.
I might add the reset one in next version

**Comment by GiuseppeChillemi** [comment]
> yes, they change the behaviour until they are changed again.

Do you mean they are mantained between script starts ?

**Comment by mmarcincin** [comment]
As long as those switches are part of links.txt they override the default behavior for links under them. My script allows you to continue with downloading without the need to remove the links from the links.txt. It's useful if you downloaded bundle partially, otherwise it might delay the downloading by checking previous bundles, especially if there's a lot of downloaded bundle links.

The script runs through the links.txt with each launch. It executes things from top to bottom.
That's what !md5s+ is for, you can put the bundles links already downloaded and it'll check if they were correctly downloaded (as long as you didn't take them out of downloads folder or renamed them).

**Comment by mmarcincin** [comment]
Added/Clarified in README for version 0.3.7
