### ISSUE TITLE
Internet Explorer errors while trying to run script in Windows 11

### ISSUE THREAD

**Issue by RainMercury** [mmarcincin/HB-DRM-free-bulk-downloader#18]
Internet Explorer provides following errors:

Line: 1
Error: 'fetch' is undefined

Line: 1
Error: Object doesn't support property or method 'append'

Line: 1
Error: 'fetch' is undefined

Line: 5
Error: Syntax error

Is it possible to add support for Chrome, Opera, Firefox, or even Edge?

**Comment by mmarcincin** [comment]
These errors looks like the ones I am getting in the Windows 10, did you switch to Internet Explorer mode in edge ?

I'll need to rewrite it so that it starts using Humble Bundle API because there's no native browser automation. It would require additional installs and that would defeat the purpose of the script (all works natively). 
There's no Internet Explorer in the windows 11 for the purpose of powershell (com object).
Even on Windows 10 the humble bundle website most likely retired the IE support completely because it was working for a while after their upgrade (the old design), that's why you see those errors. 

Unfortunately right now it's not working, you can keep watching this error thread. Once it'll start working again I'll reply here.

**Comment by mmarcincin** [comment]
I updated the script to version 0.4.0, it works without Internet Explorer now. Let me know if it works for you now.
