### ISSUE TITLE
Directory path >255 characters

### ISSUE THREAD

**Issue by GiuseppeChillemi** [mmarcincin/HB-DRM-free-bulk-downloader#9]
How,
  is it possible to truncate file paths >255 characters and write the untruncated path as filepath.txt ?  It would help managing long paths as Windows give error managing them..

**Comment by mmarcincin** [comment]
I could add some additional switch which would make shorter file/folder names.
There could be different identifier for the titles:
- for bundle name the best replacement would be specific bundle key from link  
- for DRM-free titles it would be a little bit harder, in this case the name could be left intact 
- for filenames it could be a shorter version of it since it's already represented by file title folder
Bundle name would definitely save some length but for filename I'd have to set some specific length which it shouldn't go over. 
I could run a script through my current bundles to find the usual length of filenames.

If you are dealing with the files in Windows 10 only then you could try this to enable long paths:
https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file#enable-long-paths-in-windows-10-version-1607-and-later

**Comment by mmarcincin** [comment]
I updated the script to version 0.4.0. 
I implemented the bundle name reduction and conditional filename reduction which you can specify based on your preferences. 
It's part of the switches for my script which you place directly into links.txt:
~if_title-60_file-30 that means if the title name is longer than 60, it'll shorten the filename to 30. You can change the values how you'd like. (see README)

Let me know if it helped with your issue :)
